### ISSUE TITLE
Repo rights for creating github secrets to facilitate a quay.io push?

### ISSUE THREAD

**Issue by jameshowison** [2i2c-org/utexas-image#5]
### Context

Trying to follow process to build and push image to quay.io.  Discussion at https://github.com/2i2c-org/hub-user-image-template/pull/10 and https://github.com/2i2c-org/infrastructure/issues/1158

I understand that I need to provide the quay.io username and password as Github Secrets on the repository.  Clicking into repository settings I don't see "Secrets" on the left hand menu.  I see:

![Screen Shot 2022-03-31 at 9 27 57 AM](https://user-images.githubusercontent.com/91986/161079296-202bdd91-00eb-4ce7-8b81-207bf2695223.png)

Perhaps I need additional rights on this repo to set up secrets?  Experimenting with "assigning" people I think might help, feels a bit controlling :)

**Comment by choldgraf** [comment]
@jameshowison I noticed you were a "maintainer" in this repo. I just changed that to "admin" which I think gives you as many permissions as possible. Does this make the secrets tab show up?

**Comment by yuvipanda** [comment]
@jameshowison ah, this is already all set up for this repo! You can see it in https://quay.io/repository/2i2c/utexas-image?tab=tags. We should probably update the README...

**Comment by yuvipanda** [comment]
I can see that your latest PR (#4) was built and pushed, as 12fef86b7c18 - https://quay.io/repository/2i2c/utexas-image?tab=tags

**Comment by jameshowison** [comment]
Great.  Weird thing is that I checked that quay repo after the github
action task completed and I didn't see it there.  I'm not quite grokking
the sequence yet, but this makes more sense as it worked last time too!

**Comment by jameshowison** [comment]
FWIW yes, that change to "Admin" did make the secrets visible, but as @yuvipanda points out I didn't need them.  No worries if change back to maintainer becuase that is what self-service admins would usually be on these image repos, I think.
